package NotePad;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author MD SHAMIM
 */
public class Panel2 extends javax.swing.JPanel {

    int Index, SelectedIndex, Id;
    String Name, Text;
    DBConnection db = new DBConnection();
    DefaultListModel dml_name = new DefaultListModel();
    DefaultListModel dml_text = new DefaultListModel();
    DefaultListModel dml_index = new DefaultListModel();

    public Panel2() {
        initComponents();
        try {
            String query = "select *from notelist";
            db.rs = db.st.executeQuery(query);
            while (db.rs.next()) {
                Name = db.rs.getString("Name");
                Id = db.rs.getInt("ID");
                Text = db.rs.getString("Text");
                dml_name.addElement(Name);
                dml_text.addElement(Text);
                dml_index.addElement(Id);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
        ListView.setModel(dml_name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextField = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListView = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 255));

        TextField.setBackground(new java.awt.Color(204, 204, 204));
        TextField.setColumns(20);
        TextField.setLineWrap(true);
        TextField.setRows(5);
        jScrollPane1.setViewportView(TextField);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Details Text");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("List Of Note");

        ListView.setBackground(new java.awt.Color(204, 204, 204));
        ListView.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "shamim", "romim" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListViewMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListView);

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        String UpdateText = TextField.getText();
        try
        {
            db.st.executeUpdate("UPDATE `notelist` SET `Text`= '" + UpdateText + "'"
                    + " WHERE `ID` = '" + SelectedIndex + "'");
            
            
            dml_name.clear();
            dml_text.clear();
            dml_index.clear();

            String query = "select *from notelist";
            db.rs = db.st.executeQuery(query);
            while (db.rs.next()) {
                Name = db.rs.getString("Name");
                Text = db.rs.getString("Text");
                Id = db.rs.getInt("ID");
                dml_name.addElement(Name);
                dml_text.addElement(Text);
                dml_index.addElement(Id);
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ListViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListViewMouseClicked
        Index = ListView.getSelectedIndex(); 
        SelectedIndex = (Integer) dml_index.getElementAt(Index);
        String select = dml_text.getElementAt(Index).toString();
        TextField.setText(select);
    }//GEN-LAST:event_ListViewMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = ListView.getSelectedValue();
        String text = TextField.getText();
        
        try {
            db.st.executeUpdate("Delete from notelist WHERE Name = '" + name + "' AND Text = '"
                    + text + "' AND ID = '" + SelectedIndex + "'");

            dml_name.clear();
            dml_text.clear();
            dml_index.clear();

            String query = "select *from notelist";
            db.rs = db.st.executeQuery(query);
            while (db.rs.next()) {
                Name = db.rs.getString("Name");
                Text = db.rs.getString("Text");
                Id = db.rs.getInt("ID");
                dml_name.addElement(Name);
                dml_text.addElement(Text);
                dml_index.addElement(Id);
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }

        TextField.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        dml_name.clear();
        dml_text.clear();
        dml_index.clear();
        
        try {
            String query = "select *from notelist";
            db.rs = db.st.executeQuery(query);
            while (db.rs.next()) {
                Name = db.rs.getString("Name");
                Text = db.rs.getString("Text");
                Id = db.rs.getInt("ID");
                dml_name.addElement(Name);
                dml_text.addElement(Text);
                dml_index.addElement(Id);
            }
            TextField.setText("");

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JList<String> ListView;
    protected javax.swing.JTextArea TextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
